@baseUrl = http://localhost:5000/api


GET {{baseUrl}}/albums?limit=2
Accept: application/json
###

GET {{baseUrl}}/albums
Accept: application/json
###

GET {{baseUrl}}/albums/new
Accept: application/json
